# -*- coding: utf-8 -*-
"""ANN_seq_200.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lvRN9zEGVixsz9kTv5aKN9zAkvyuT9va
"""

from google.colab import drive
drive.mount('/content/drive')

drive.mount("/content/drive", force_remount=True)

# -*- coding: utf-8 -*-
"""
Created on Mon Aug 12 16:02:52 2019

@author: Pias Tanmoy
"""


from __future__ import print_function
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers.core import Activation
from keras.layers import Dropout
from keras.optimizers import SGD
from keras.optimizers import Adam
from keras.utils import np_utils
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.utils.multiclass import unique_labels
from sklearn.utils import shuffle
import pandas as pd
from keras.callbacks import ModelCheckpoint
from keras.utils import to_categorical
import glob
from sklearn.model_selection import train_test_split
import keras
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

np.random.seed(0)
N_EPOCH = 20
BATCH_SIZE = 50
VERBOSE = 1
N_CLASS = 2
OPTIMIZER = Adam()
N_HIDDEN_1 = 128
VALIDATION_SPLIT = 0.2
RESHAPE = 784
DROPOUT = 0.1



x = pd.read_csv('/content/drive/My Drive/Google_Colab/HAR/dataset/X_5000_seq_200_test.csv')
y = pd.read_csv('/content/drive/My Drive/Google_Colab/HAR/dataset/Y_5000_seq_200_test.csv')
#x_test = pd.read_csv('/content/drive/My Drive/Google_Colab/HAR/dataset/X_5000_seq_200_test.csv')
#y_test = pd.read_csv('/content/drive/My Drive/Google_Colab/HAR/dataset/Y_5000_seq_200_test.csv')

y = y.astype(int)
onehotencoder = OneHotEncoder(categorical_features = [0])
y = onehotencoder.fit_transform(y).toarray()

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)

y_train = y_train.astype(int)
y_test = y_test.astype(int)


#X_train, Y_train = shuffle(X_train, y_train)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

x_train.shape

DROPOUT = 0.5
def create_model():
  classifier = Sequential()
  classifier.add(Dense(units = 500, activation='relu', kernel_initializer='glorot_uniform', input_dim=1200))
  classifier.add(Dropout(DROPOUT))
  classifier.add(Dense(units = 100, activation='relu', kernel_initializer = 'glorot_uniform'))
  classifier.add(Dropout(DROPOUT))
  classifier.add(Dense(units = 50, activation='relu', kernel_initializer = 'glorot_uniform'))
  classifier.add(Dropout(DROPOUT))
  classifier.add(Dense(units = 500, activation='relu', kernel_initializer = 'glorot_uniform'))
  classifier.add(Dense(units = 2, kernel_initializer = 'uniform', activation = 'softmax'))
  classifier.compile(optimizer = 'Adam' , loss = 'categorical_crossentropy', metrics = ['accuracy'])
  model = classifier
  
  return model

model = create_model()

#model = create_model()

BATCH_SIZE = 20
VALIDATION_SPLIT = 0.2

history = model.fit(x_train, y_train, batch_size = BATCH_SIZE, 
                    epochs = 50, verbose = VERBOSE, 
                    validation_split=VALIDATION_SPLIT,
                    shuffle = True)

scores = model.evaluate(x_test, y_test, verbose=1)
print("Test Score: ", scores[0])
print("Accuracy: " , scores[1])


y_pred = model.predict(x_test)
y_test_argmax = y_test.argmax(axis=1)
y_pred_argmax = y_pred.argmax(axis=1)

from sklearn.metrics import f1_score
print('sklearn Macro-F1-Score:', f1_score(y_test_argmax, y_pred_argmax, average='macro'))

print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'validation'], loc='upper left')

from google.colab import files
plt.savefig("acc.png", dpi=300)
#files.download("acc.png") 
plt.show()


# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'validation'], loc='upper left')
plt.savefig("loss.png", dpi=300)
#files.download("loss.png") 
plt.show()

def plot_confusion_matrix(y_true, y_pred, classes,
                          normalize=False,
                          title=None,
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if not title:
        if normalize:
            title = 'Normalized confusion matrix'
        else:
            title = 'Confusion matrix, without normalization'

    # Compute confusion matrix
    cm = confusion_matrix(y_true, y_pred)
    # Only use the labels that appear in the data
    classes = classes[unique_labels(y_true, y_pred)]
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    fig, ax = plt.subplots()
    im = ax.imshow(cm, interpolation='nearest', cmap=cmap)
    ax.figure.colorbar(im, ax=ax)
    # We want to show all ticks...
    ax.set(xticks=np.arange(cm.shape[1]),
           yticks=np.arange(cm.shape[0]),
           # ... and label them with the respective list entries
           xticklabels=classes, yticklabels=classes,
           title=title,
           ylabel='True label',
           xlabel='Predicted label')

    # Rotate the tick labels and set their alignment.
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
             rotation_mode="anchor")

    # Loop over data dimensions and create text annotations.
    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, format(cm[i, j], fmt),
                    ha="center", va="center",
                    color="white" if cm[i, j] > thresh else "black")
    fig.tight_layout()
    return ax


np.set_printoptions(precision=2)

from sklearn.metrics import confusion_matrix
y_pred = model.predict(x_test)
y_test_argmax = y_test.argmax(axis=1)
y_pred_argmax = y_pred.argmax(axis=1)

class_names = np.array([0, 1, 2])

# Plot non-normalized confusion matrix
plot_confusion_matrix(y_test_argmax, y_pred_argmax, classes=class_names,
                      title='Confusion matrix, without normalization')

plt.savefig('confusion_mat_count.png', dpi=300)
# Plot normalized confusion matrix
plot_confusion_matrix(y_test_argmax, y_pred_argmax, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')
plt.savefig('confusion_mat_%.png', dpi=300)

plt.show()

